# Generated by Django 5.0.6 on 2026-05-26 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text="e.g. 'diesel', 'natural_gas', 'electricity_uk', 'flight_economy'", max_length=100)),
                ('unit', models.CharField(help_text='Standardized unit: litres, kWh, miles, kg, passenger-km', max_length=50)),
                ('kg_co2e_per_unit', models.FloatField(help_text='Emission intensity in kg CO2e per unit of activity')),
                ('scope', models.CharField(choices=[('1', 'Scope 1 — Direct'), ('2', 'Scope 2 — Electricity'), ('3', 'Scope 3 — Value Chain')], max_length=1)),
                ('source', models.CharField(choices=[('DEFRA', 'UK DEFRA 2023'), ('EPA', 'US EPA eGRID'), ('IPCC', 'IPCC AR6')], default='DEFRA', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scope', 'activity_type'],
                'unique_together': {('activity_type', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility — Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('row_count', models.IntegerField(default=0, help_text='Total rows parsed from CSV')),
                ('error_count', models.IntegerField(default=0, help_text='Rows that failed to parse')),
                ('error_detail', models.TextField(blank=True, help_text='Error message if status=FAILED')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField(blank=True, help_text='Standardized activity/transaction date in YYYY-MM-DD', null=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility — Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('scope', models.CharField(blank=True, choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('category', models.CharField(blank=True, help_text="Human-readable category: 'Diesel Fuel', 'Grid Electricity', 'Flight — Economy'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Human-readable activity description from source data')),
                ('location', models.CharField(blank=True, help_text='Facility, site, or city extracted from source', max_length=255)),
                ('supplier_vendor', models.CharField(blank=True, help_text='Vendor name from SAP or airline from travel records', max_length=255)),
                ('activity_value', models.FloatField(blank=True, help_text='Standardized quantity (e.g. litres of fuel, kWh of electricity, km of travel)', null=True)),
                ('activity_unit', models.CharField(blank=True, help_text="Standardized unit: 'litres', 'kWh', 'passenger-km'", max_length=50)),
                ('emission_factor_value', models.FloatField(blank=True, help_text='Snapshot of EF kg_co2e_per_unit at time of calculation. Persisted for auditability.', null=True)),
                ('calculated_emissions_kg', models.FloatField(blank=True, help_text='activity_value * emission_factor_value. Stored in kg CO2e.', null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('flag_reason', models.TextField(blank=True, help_text='Auto-populated for system flags; analyst-written for manual flags')),
                ('is_auto_flagged', models.BooleanField(default=False, help_text="True if this record was flagged by the parser's validation rules")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('edited_fields', models.JSONField(blank=True, default=dict, help_text='Tracks manual edits: {field: {old: ..., new: ...}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, help_text='The EF used for calculation. SET_NULL so records survive EF updates.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.emissionfactor')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.ingestionjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', 'source_type'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Record Created'), ('EDIT', 'Field Edited'), ('APPROVE', 'Approved'), ('FLAG', 'Flagged by Analyst'), ('REJECT', 'Rejected'), ('SYSTEM_FLAG', 'Auto-flagged by System')], max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('field_changes', models.JSONField(blank=True, default=dict, help_text='{field_name: {before: old_value, after: new_value}}')),
                ('note', models.TextField(blank=True, help_text='Analyst note or rejection reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(help_text='0-based row index within the source CSV')),
                ('row_data', models.JSONField(help_text='Raw CSV row as {column: value} dict')),
                ('parse_error', models.TextField(blank=True, help_text='Non-empty if this row failed normalization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['job', 'row_index'],
                'unique_together': {('job', 'row_index')},
            },
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(help_text='The source raw row this was derived from', on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.tenant'),
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('reviewer', 'Reviewer')], default='analyst', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ingestion.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_n_tenant__012efe_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='ingestion_n_tenant__3a03cc_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingestion_n_tenant__14f5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['activity_date'], name='ingestion_n_activit_ef9478_idx'),
        ),
    ]
